### ISSUE TITLE
Is it possible to overwrite and reinstall a clean debian (with zfs root) over an existing debian/ubuntu?

### ISSUE THREAD

**Issue by orange888** [hn/debian-buster-zfs-root#7]
Is it possible to overwrite and reinstall a clean debian (with zfs root) over an existing debian/ubuntu?

The reason is to avoid using the Live Boot CD altogether. It would be much quicker. Thanks.

**Comment by hn** [comment]
The script wipes the complete disk / partition table of the selected target drives. Having a system running on those very same drives is not possible.

Plugging in and booting an USB stick is easy ...
